language: python
python:
    - "2.7"

install: "pip install -r requirements/development.txt"

script:
    - coverage run manage.py test eggtimer --settings=eggtimer.settings.development
    - flake8

after_success:
    coveralls
