language: python
python:
    - "2.7"

# command to install dependencies
install: "pip install -r requirements/development.txt"

# command to run tests
script: python manage.py test --settings=eggtimer.settings.development --with-coverage && flake8

after_success:
    coveralls
