language: python
python:
    - "2.7"
    - "3.4"

before_script:
  - npm install jshint mocha blanket mocha-lcov-reporter

install: "pip install -r requirements/development.txt"

script:
    - coverage run manage.py test --settings=eggtimer.settings.development
    - flake8
    - NODE_ENV=test EGGTIMER_COVERAGE=1 mocha --reporter json-cov */tests/static/js/* > coverage.json
    - jshint */static/js

# TODO coveralls isn't showing django template coverage or javascript coverage
after_success:
    coveralls --merge coverage.json
