language: python
python:
    - "2.7"
    - "3.4"

install:
    - pip install -r requirements/development.txt
    - gem install coveralls-lcov

before_script:
  - npm install jshint mocha blanket mocha-lcov-reporter

script:
    - coverage run manage.py test --settings=eggtimer.settings.development
    - flake8
    - NODE_ENV=test EGGTIMER_COVERAGE=1 mocha --reporter mocha-lcov-reporter */tests/static/js/* > coverage.info
    - coveralls-lcov -v -n coverage.info > coverage.json
    - jshint */static/js

after_success:
    coveralls --merge coverage.json
